### ISSUE TITLE
CD/CD [ERROR] - Install Prisma Client

### ISSUE THREAD

**Issue by diogenesOliver** [diogenesOliver/Task-s#14]
CI/CD had an error installing the `@prisma/client` dependency. Every time a commit was generated, the automation could not continue because it was blocking the installation of this dependency. To solve this deadlock, in the CI/CD yaml code an `npm audit fix --force` was added, after this change the CI/CD returned to normal.

See the change made to the code below:

```yaml
- name: Install dependencies
      run: |
        npm audit fix --force
        npm install
```
